### ISSUE TITLE
Allowing search to sort by most recent, also by labels/types of notebooks e.g ability to search notebooks built on vegalite

### ISSUE THREAD

**Issue by KudakwasheMushaike** [observablehq/feedback#97] opened 2021-05-13 20:53 UTC
From Forum user, PBrockmann

"It would be nice to be able to sort by date (most recent to older) results when you search a keyword from all available notebooks.

Would be nice also to put keywords to define notebooks (technics and meanings)?
For example, I would like to browse all notebooks made recently that use vega-lite or find notebooks about Sankey diagram that uses d3.

Regards
Patrick"

**Comment by jrus** [comment] 2021-05-14 08:06
This looks like a duplicate of https://github.com/observablehq/feedback/issues/93

**Closed** 2021-06-27 13:37 UTC
Labels: Feature Request
