### ISSUE TITLE
Set URL with trailing suffix crashes when suffix deleted in URL chooser dialog

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#472] opened 2022-08-11 05:40 UTC
**Describe the bug**
The URL chooser hard crashes the application when removing a slash suffix.

1. set URL
2. add a suffix, e.g. /2
3. delete the /2
The page crashes which clientside error (on Chrome Desktop)

Demo:
https://user-images.githubusercontent.com/1848162/184070656-e5eb2788-9dd2-4b7f-803e-9d4b3df66545.mov

**Comment by CobusT** [comment] 2022-08-11 06:01
Thanks for raising. We are redoing these modals and will fix as part of that effort.
Duplicate of #318

**Comment by CobusT** [comment] 2022-08-15 20:10
This is now fixed.

**Closed by CobusT** 2022-08-15 20:10 UTC
Labels: Bug
