### ISSUE TITLE
Find and Replace feature does not move to the next item in some cases

### ISSUE THREAD

**Issue by EE2dev** [observablehq/feedback#548] opened 2023-03-04 13:03 UTC
**Describe the bug**

I type "frac" into  the find box "dfrac" into the replace box. Replacing an item does so, but it doesn't move to the next occurence. Instead it highlights the "frac" part of the new "dfrad". So if I hit replace twice it creates "ddfrac" from the intial "frac". 

**Expected behavior**
After replacing the next occurence should be selected and highlighted

**Comment by mootari** [comment] 2023-03-04 13:38
This seems to be a duplicate of https://github.com/observablehq/feedback/issues/354.

**Closed** 2023-03-04 13:39 UTC
