### ISSUE TITLE
renaming a cell docs are incorrect

### ISSUE THREAD

**Issue by espinielli** [observablehq/feedback#644] opened 2024-09-05 09:36 UTC
**Describe the bug**
The documentation for [naming a cell](https://observablehq.com/documentation/cells/#naming-cells) is not in line with what is actually possible in a notebook.

**To Reproduce**
The documentation for a markdown cell shows you can name it as in the following snapshot
![image](https://github.com/user-attachments/assets/2e436f39-77e2-46fc-b3c0-d41e0798000c)

but there si not such a field where to enter the name of the cell:
![image](https://github.com/user-attachments/assets/fe5cdaee-2e8e-464b-a148-1d6ded6029ec)

Also there is no possibility to similarly name HTML cells (which exist as in [this official Observable notebook](https://observablehq.com/@observablehq/custom-plot-themes#myGoogleFonts))

The only way to name markdown and HTML cells I found is to use something like (in a javascript cell)
```
myname = md`my text`
```
or for HTML (in a javascript cell)
```
mystyle = html`<style></style>`
```

**Expected behavior**
I think the docs should be updated to reflect the current implementation and extended to include missing bits.

**Desktop (please complete the following information):**
 platform: 
  - OS: macOS 14.5 MBP M1 Max, 
    Browser: Arc 1.58.1 (53264)
  - OS:MS Windows 10 Enterprise 10.0.19045
    Browser: Edge Version 128.0.2739.63 (Official build) (64-bit)

**Comment by mootari** [comment] 2024-09-05 10:18
@espinielli When you focus a cell, do you see the toolbar at the bottom of the window?

**Comment by espinielli** [comment] 2024-09-05 11:13
yes as per my second picture...the toolbar is at the bottom of the _cell_

**Comment by mootari** [comment] 2024-09-05 11:19
The documentation is correct, but does not account for the changes that we apply for touch devices (which we also detect when you use a touch screen).

I'm going to close this as a duplicate of #582, but please upvote that issue and add your details there so that we have a better idea of how many folks are affected by this problem.

**Closed as not planned by mootari** 2024-09-05 11:19 UTC

**Comment by espinielli** [comment] 2024-09-05 11:22
I am not on a touch-enabled device...
