### ISSUE TITLE
editing toolbar broken on first cell before editing

### ISSUE THREAD

**Issue by triptych** [observablehq/feedback#280] opened 2021-11-04 05:43 UTC
**Describe the bug**

The new integrated toolbar shows up on the right in a broken state when editing a brand new blank notebook. See screenshots below.

**To Reproduce**
1. go to observablehq.com
2. create a new blank notebook
3. focus cursor in first cell

**Expected behavior**
Expect toolbar to be below the cell. Instead it's to the right in a weird broken state.

**Screenshots**
Chrome:
<img width="960" alt="chrome_De93fQDGFl" src="https://user-images.githubusercontent.com/8691/140263517-9ae6aad6-bd96-4fe7-9793-92878c0ac701.png">

Firefox:
<img width="960" alt="firefox_c2j6rfMtOu" src="https://user-images.githubusercontent.com/8691/140263562-c73e5ea5-dba9-4d38-a466-1cee595b2308.png">

**Desktop (please complete the following information):**
- OS Window
-  Chrome Version 95.0.4638.69 (Official Build) (64-bit)
- OS Info:
- 
Device name	DESKTOP-ACN1IPP
Processor	Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	D2C430AF-398B-4796-8FF7-BDAFBD508D6C
Product ID	00325-81370-62044-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

**Additional context**

I suspect that since I am using an all-in-one laptop with a touch screen whatever Observable is doing to detect for touch is interfering with the display. 
This is not caused by some plugin because the behavior happens even in incognito window.

Note: reloading the blank notebook does not change the behavior, but EDITING a cell and reloading will cause the toolbar to drop down and appear as it should.  This only happens for the initial state before a cell is edited, and even then the page has to be reloaded ( probably changing the code decision path for the rendering ) before the right toolbar shows up

**Comment by triptych** [comment] 2021-11-04 05:50
Here's a notebook that demonstrates the issue - I've never edited the initial cell so it stays in the "broken" state https://observablehq.com/@triptych/untitled/2

**Comment by CobusT** [comment] 2021-11-04 06:04
Thanks for the bug report, and your great additional context. This is very likely a bug related to our detection of touch support.

**Comment by mootari** [comment] 2021-11-04 14:55
> This is very likely a bug related to our detection of touch support.

@CobusT I think these are distinct issues:
- This particular issue is primarily about a broken layout for the first cell, and should be reproducible on any device (as well as e.g. Chrome with an active mobile device toolbar)
- The other, imo independent, issue is that Observable tests for touch support to determine wether the toolbar should be displayed within the cell or at the bottom. Judging from the additional context given by @mbostock in Slack, the original intent was to work around the positioning problems in browsers with a mobile address bar (i.e. shown/hidden on scroll).

**Comment by mbostock** [comment] 2021-11-04 15:03
This was a framework bug in server-side rendering and hydration, not in our application code. A fix will be released shortly.

**Closed** 2021-11-04 15:39 UTC
Labels: Bug

**Comment by CobusT** [comment] 2021-11-04 16:43
Should be ready to test!

**Comment by triptych** [comment] 2021-11-04 18:25
What I see now: 
![image](https://user-images.githubusercontent.com/8691/140397467-1b6c6f80-d971-437a-8648-586c61abe59e.png)

Which fixes the First time loading brokenness of the toolbar.

@mootari is correct that while the bar is rendering nicely now, it's still in the "inline" toolbar mode vs the "footer" toolbar of a non-touch device. 

That could be a subject for another bug, but my initial issue posted for this bug is fixed.

**Comment by mbostock** [comment] 2021-11-04 18:32
That’s currently the intended behavior, Andrew. We’ll let you know if we change it. 👍

**Comment by mootari** [comment] 2021-11-06 12:54
> That’s currently the intended behavior, Andrew. We’ll let you know if we change it. 👍

@mbostock I think there may be a misunderstanding here. From what I understand Andrew has a "normal" laptop with a touchpad and the ability to use a mouse. This laptop also has a touchscreen, but the touch screen is *not* the primary input method.

**Comment by mbostock** [comment] 2021-11-06 14:32
That was my interpretation, @mootari. I similarly have an iPad with a physical keyboard that gets the inline toolbar treatment. We use touch support as a proxy for whether the device is likely to have a virtual onscreen keyboard rather than a physical keyboard. (And, to a lesser degree, to avoid iOS’s wonky position-fixed implementation when an input is focused.) As far as I’m aware, there’s no standard way of querying wether a device has a physical keyboard.

**Comment by triptych** [comment] 2021-11-06 16:16
This is accurate. I have an HP Pavilion which is an 'all-in-one' with a touch screen. I'm ok with having both ( My mac laptop has the toolbar at the bottom ) .  One possible option - could we override the "detection" and choose which version of the toolbar we want --> inline / footer as a configurable override?
