### ISSUE TITLE
SharedArrayBuffer support

### ISSUE THREAD

**Issue by tomlarkworthy** [observablehq/feedback#615] opened 2024-01-11 23:55 UTC
**Is your feature request related to a problem? Please describe.**
Synchronous cross worker function call emulation is not possible without SharedArrayBuffer, Atomics.wait(), Atomics.notify(). We do not have the required response headers on the content document

```
"Cross-Origin-Opener-Policy": "same-origin"
"Cross-Origin-Embedder-Policy": "require-corp"
```

These are needed to get WASI working. To emulate blocking access to filesystem handles, the WASM worker needs to be paused until JS has a response, and thus the need for Atomics over shared buffers is born. See https://github.com/wasmerio/wasmer-js

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mootari** [comment] 2024-01-12 11:30
There was a similar discussion [for WebR](https://github.com/observablehq/feedback/issues/557) when it still required SharedArrayBuffer, and this issue is essentially a duplicate of #532.

Last time I investigated this my conclusion was that it's simply not possible with Observable's sandbox architecture. I'm going to close this issue for now, but happy to reopen if I'm proven wrong. 🙂 

If you like you can give it a shot by [overriding headers](https://developer.chrome.com/docs/devtools/overrides) via Chrome DevTools.

**Closed as not planned by mootari** 2024-01-12 11:30 UTC

**Comment by tomlarkworthy** [comment] 2024-01-14 16:24
yes its the same issue. I saw those were motivated by R though and solved a different way. This is a blocker for WASI though. Maybe not possible to fix in any sane way though.
