### ISSUE TITLE
Maintain collection when fork notebooks

### ISSUE THREAD

**Issue by sugi2000** [observablehq/feedback#558] opened 2023-03-30 07:12 UTC
**Is your feature request related to a problem? Please describe.**
When I fork my notebook in a specific collection, I always have to add a new notebook to the collection.

**Describe the solution you'd like**
The modal dialog when forking should have a checkbox for maintaining the original collection or a select menu of collections.

**Comment by CobusT** [comment] 2023-03-30 13:42
Duplicate of #497?

**Closed** 2023-04-25 22:51 UTC
