### ISSUE TITLE
copy shortcut without selection should not modify the clipboard

### ISSUE THREAD

**Issue by jrus** [observablehq/feedback#53] opened 2021-03-19 22:46 UTC
**Description:** Observable cell editors copy the current line when the operating system copy shortcut (on a Mac, command-C) is pressed. This does not match other text boxes inside or outside the browser, and is confusing. Sometimes copy is pressed by mistake instead of paste, resulting in a clobbered clipboard (potentially lost data).

**Steps to reproduce:** Focus a non-empty line of code in an Observable cell editor with no selection and (on a Mac) press command-C.

**Expected behavior:** An error beep and an unchanged clipboard.

**Actual behavior:** The current line is copied to the clipboard, overwriting whatever was there before.

**Discussion:** Being able to copy the current line to the clipboard is sometimes helpful, but it should be assigned its own unique keyboard shortcut instead of re-using the generic Copy shortcut.

**Comment by j-f1** [comment] 2021-03-20 01:20
This feature is fairly common in other code editors like Atom and VS Code.

**Comment by jrus** [comment] 2021-03-20 06:08
Someone should file a bug report with those too. :-)

**Comment by mootari** [comment] 2021-03-20 14:14
@jrus Like @j-f1 mentioned, copying the line is a common behavior in IDEs and coding environments (e.g. GitHub, Codepen, Glitch ... I could go on), and should not be delegated to a separate shortcut.

**Comment by jrus** [comment] 2021-03-20 23:10
Well I personally find this behavior quite frustrating. Inability for users to make the editor behave like their basic expectations or meet their particular needs is the big downside of having a 1-size-fits-all browser-box editor experience. A read-write API could help work around this defect, https://github.com/observablehq/feedback/issues/6

**Comment by CobusT** [comment] 2021-08-03 15:29
Closing this since this is intended behavior.

**Closed by CobusT** 2021-08-03 15:29 UTC
Labels: Won't Fix
